# Generated by Django 4.2.28 on 2026-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='question_media/%Y/%m/%d/'),
        ),
    ]
