# Generated by Django 4.2.30 on 2026-06-10 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0004_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='forms_api.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'form')},
            },
        ),
    ]
