# Generated by Django 4.2.30 on 2026-07-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0005_formarchive_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formpermission',
            new_name='formperm_form_user_perm_idx',
            old_name='forms_api_formperm_form_user_idx',
        ),
        migrations.RenameIndex(
            model_name='response',
            new_name='response_form_created_idx',
            old_name='forms_api_response_form_created_idx',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='answers', to='forms_api.question'),
        ),
    ]
