# Generated by Django 4.2.30 on 2026-09-30 11:44

from django.db import migrations, models
import forms_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0006_rename_forms_api_formperm_form_user_idx_formperm_form_user_perm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='file_answer',
            field=models.FileField(blank=True, null=True, upload_to=forms_api.models.answer_upload_to),
        ),
        migrations.AlterField(
            model_name='form',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/%Y/%m/'),
        ),
    ]
